Product.create!([
  {name: "Powerslide Next 110 Pro", image_url: "https://media.grindhouse.eu/CommerceManager/Products/7294/product_7294_5e2095c2451a3_medium.jpg"},
  {name: "FR1 310 Red", image_url: "https://media.grindhouse.eu/CommerceManager/Products/6501/product_6501_5b699623b5609_medium.jpg"},
  {name: "Powerslide HC Evo Pro 90 2021", image_url: "https://media.grindhouse.eu/CommerceManager/Products/7598/product_7598_60084cc343759_large.jpg"},
  {name: "Powerslide Zoom Pro Lomax 110", image_url: "https://www.xtremeinn.com/f/13796/137966383/powerslide-zoom-pro-lomax-110-inline-skates.jpg"}
])

Shop.create!([
  {host: "www.der-rollenshop.de", price_selector: "meta[itemprop='price']", currency_selector: "meta[itemprop='priceCurrency']", description_selector: "meta[name='description']"},
  {host: "bladeville.com", price_selector: "span[itemprop='price']", currency_selector: "meta[itemprop='priceCurrency']", description_selector: "meta[name='description']"},
  {host: "www.grindhouse.eu", price_selector: "meta[itemprop='price']", currency_selector: "meta[itemprop='priceCurrency']", description_selector: "meta[name='description']"},
  {host: "www.inercia.com", price_selector: "meta[itemprop='price']", currency_selector: "meta[itemprop='priceCurrency']", description_selector: "meta[name='description']"},
  {host: "www.rollernco.com", price_selector: "span[itemprop='price']", currency_selector: "meta[itemprop='priceCurrency']", description_selector: "meta[name='description']"},
  {host: "www.skatepro.net", price_selector: "span[itemprop='price']", currency_selector: "meta[itemprop='priceCurrency']", description_selector: "meta[name='description']"},
  {host: "www.prosports.si", price_selector: "span[itemprop='price']", currency_selector: "meta[itemprop='priceCurrency']", description_selector: "meta[name='description']"},
  {host: "www.nomadeshop.com", price_selector: "div[itemprop='price']", currency_selector: "meta[itemprop='priceCurrency']", description_selector: "meta[name='description']"},
  {host: "www.locoskates.com", price_selector: "meta[property='og:price:amount']", currency_selector: "meta[itemprop='priceCurrency']", description_selector: "meta[name='description']"},
  {host: "www.skamidan.com", price_selector: ".legacy-itemprop-offers .woocommerce-Price-amount.amount bdi", currency_selector: ".legacy-itemprop-offers .woocommerce-Price-currencySymbol", description_selector: "meta[name='description']"},
  {host: "www.coolskates.cz", price_selector: "meta[itemprop='price']", currency_selector: "meta[itemprop='priceCurrency']", description_selector: "meta[name='description']"},
  {host: "www.slidingtiger.eu", price_selector: "#SingleProductTitle > div:first > div", currency_selector: "#SingleProductTitle > div:first > div", description_selector: "meta[name='description']"},
  {host: "www.thisissoul.com", price_selector: ".product__price .price__regular .price-item", currency_selector: ".product__price .price__regular .price-item", description_selector: "meta[name='description']"},
  {host: "www.xtremeinn.com", price_selector: "meta[itemprop='price']", currency_selector: "meta[itemprop='priceCurrency']", description_selector: "meta[name='description']"},
  {host: "www.in-gravity.com", price_selector: "#precio_principal span[itemprop='price']", currency_selector: "meta[itemprop='priceCurrency']", description_selector: "meta[name='description']"},
  {host: "www.hgshop.hr", price_selector: ".product-price .new .price .value", currency_selector: ".product-price .new .price .currency", description_selector: "meta[name='description']"},
  {host: "itaksport.com", price_selector: "meta[property=\"product:price:amount\"]", currency_selector: "meta[property='product:price:currency']", description_selector: "meta[name='description']"}
])

Page.create!([
  {url: "https://bladeville.com/powerslide-hardcore-evo-pro-90-black-red.html", product_id: 1, shop_id: 2, price: "599.99", currency: "EUR", description: "Powerslide Hardcore EVO PRO  is the latest iteration of the excellent freestyle slalom skate from Powerslide These groundbreaking carbon skates are fully heatmoldable and come with Trinity mounting for maximum efficiency"},
  {url: "https://www.grindhouse.eu/en/shop/inline-skates/powerslide-hc-evo-pro-90.html", product_id: 1, shop_id: 3, price: "599.95", currency: "EUR", description: "POWERSLIDE HC Evo Pro  - High-end freestyle skate with a heat mouldable padding carbon shell Trinity frame and xmm wheels!"},
  {url: "https://www.inercia.com/en/powerslide-hc-evo-pro-90.html", product_id: 1, shop_id: 4, price: "599.99", currency: "EUR", description: "<p>The third generation is coming in a new look based on a mix of nylon mesh and PU-leather including a TPU panel for extra lateral support The patented Trinity mounting boosts your performance to another level thanks to the incredible power transfer and"},
  {url: "https://www.der-rollenshop.de/Powerslide-Inline-Skates-HC-Evo-Pro-90", product_id: 1, shop_id: 1, price: "599.0", currency: "EUR", description: "Powerslide HC Evo  - The pinnacle of freestyle skating The Powerslide HC Evo  is loved for its great performance and comfort right out of the box T"},
  {url: "https://www.thisissoul.com/products/hc-evo-pro?variant=39943259455643", product_id: 1, shop_id: 13, price: "599.95", currency: "€", description: "Powerslide HC Evo - The pinnacle of freestyle skatingThe Powerslide HC Evo  is loved for its great performance and comfort right out of the box The third generation is coming in a new look based on a mix of nylon mesh and PU-leather including a TPU panel for extra lateral support The patented TRINITY mounting boost"},
  {url: "https://www.skamidan.com/produkt/powerslide-hc-evo-pro-90-black-2021-trinity-x-freestyle-inlineskates/", product_id: 1, shop_id: 10, price: "589.95", currency: "€", description: "POWERSLIDE HC Evo Pro  Black  - Der Höhepunkt des Freestyle-Skatens die Elite die lebende Legende!"},
  {url: "https://www.nomadeshop.com/roller/roller-freeskate/powerslide-roller-freeskate-hc-evo-pro-90-noir-30381.html", product_id: 1, shop_id: 8, price: "599.9", currency: "EUR", description: "Profitez de votre Roller freeskate HC EVO PRO  Noir POWERSLIDE au meilleur prix chez Nomadeshop"},
  {url: "https://www.locoskates.com/products/powerslide-hardcore-evo-pro-90-2021-skates", product_id: 1, shop_id: 9, price: "539.95", currency: "GBP", description: " Did you know that Powerslide made the first carbon fibre freestyle skate? They named it the Hardcore  as it weighed  grams The mould originated from an aggressive model called Deshi and Powerslide have developed it to be one of the leading freestyle models on the market the Powerslide Hardcore Evo Pro  "},
  {url: "https://www.in-gravity.com/powerslide-hardcore-evo-pro-90-p-1-51-18886/", product_id: 1, shop_id: 15, price: "599.99", currency: "EUR", description: "Patines Triskate Trinity Hardcore Evo Pro mm de Powerslide"},
  {url: "https://www.rollernco.com/en/completes-freeskates/11651-hc-evo-pro-90-powerslide.html", product_id: 1, shop_id: 5, price: "599.0", currency: "EUR", description: "POWERSLIDE HC Evo Pro  freeskate high performance ultra-comfortable and reactive Equipped with Trinity patented and Powerslide Spinner wheels"},
  {url: "https://bladeville.com/powerslide-next-110-pro-black.html", product_id: 2, shop_id: 2, price: "299.99", currency: "EUR", description: "We are a professional skate shop located in Poland which offers professional skates roller skates and accessories of the largest brands in the world"},
  {url: "https://www.grindhouse.eu/en/shop/inline-skates/powerslide-next-110-pro-black.html", product_id: 2, shop_id: 3, price: "299.95", currency: "EUR", description: "POWERSLIDE Next  Pro Black - Meet the next generation of urban-/freeskates - fully packed with innovative features like Trinity frame mounting etc"},
  {url: "https://bladeville.com/fr-fr1-310-red.html", product_id: 3, shop_id: 2, price: "329.99", currency: "EUR", description: "Category:&nbsp;freeride Model:&nbsp;FR  Shell:&nbsp;composite FR Liner:&nbsp;New FR liner with Premium insole Buckle:&nbsp;FK Top Buckle spider micrometic buckle lacing HDS Shock Absorber Frame:&nbsp;D /mm Wheels:&nbsp;FR Speed "},
  {url: "https://www.grindhouse.eu/en/shop/inline-skates/fr-fr1-310-red.html", product_id: 3, shop_id: 3, price: "329.95", currency: "EUR", description: "FR FR  Red - The SEBA FR series now gets their own brand SEBA FR becomes FR - different name same quality!"},
  {url: "https://www.inercia.com/en/fr-skates-fr1-310-red.html", product_id: 3, shop_id: 4, price: "329.99", currency: "EUR", description: "<p><strong>Technical characteristics</strong>:</p>\n<p>-  holes energy plates</p>\n<p>- Closure: metal top buckles double straps standard lacing</p>\n<p>- Liners: removable with removable shock absorbers</p>\n<p>- Frames: D- mm</p>\n<p>- Wheels:"},
  {url: "https://www.coolskates.cz/en/freeride/fr1-310-red/", product_id: 3, shop_id: 11, price: "332.88", currency: "EUR", description: "Kolečkové brusle FR  red pro rychlou freeride jízdu"},
  {url: "https://www.slidingtiger.eu/en/Home/Skate/UNIV-FRSK-FR1310-RD", product_id: 3, shop_id: 12, price: "329.95", currency: " €", description: "The FR  is the three-wheel version of the legendary freeride skate FR It has a liner that is as comfortable as its four-wheeled equivalent"},
  {url: "https://www.xtremeinn.com/extreme_sports/powerslide-hc-evo-pro-90-inline-skates/137966379/p", product_id: 1, shop_id: 14, price: "569.99", currency: "EUR", description: "Powerslide HC Evo Pro  Inline Skates - BlackThe Powerslide HC Evo  is loved for its great performance and comfort right out of the box extreme sports"},
  {url: "https://www.skatepro.net/121-34775.htm", product_id: 1, shop_id: 6, price: "599.95", currency: "EUR", description: "In stock Buy now for  € The HC Evo Pro are meant for urban freestyle and freeskate action On these Powerslide freeskates you ✓ Free shipping"},
  {url: "https://www.prosports.si/prosti-cas/1531-rolerji-powerslide-urban-skates-hc-evo-pro-90/#/velikost-43", product_id: 1, shop_id: 7, price: "539.97", currency: "EUR", description: "Rolerji POWERSLIDE Urban Skates HC Evo Pro "},
  {url: "https://www.xtremeinn.com/extreme_sports/powerslide-zoom-pro-lomax-110-inline-skates/137966383/p", product_id: 5, shop_id: 14, price: "237.99", currency: "EUR", description: "Powerslide Zoom Pro Lomax  Inline Skates - BlackI am super excited to finally show you my new Pro Skate the Zoom Pro Lomax from Powers extreme sports"},
  {url: "https://bladeville.com/powerslide-zoom-pro-lomax-110.html", product_id: 5, shop_id: 2, price: "270.0", currency: "EUR", description: "If you are interested in freeskating and aggressive you should know Nick Lomax His pro model of Zoom is the best edition of this freeskate so far!"},
  {url: "https://www.inercia.com/en/powerslide-zoom-pro-lomax-110-sample.html", product_id: 5, shop_id: 4, price: "199.99", currency: "EUR", description: "<p>The Powerslide Zoom Triskate is your perfect entry into the world of TRINITY our patented -point mounting system TRINITY has set a new milestone in inline skating as it offers the lowest possible center of gravity a superior power transfer improve"},
  {url: "https://www.nomadeshop.com/roller/roller-freeskate/powerslide-roller-freeskate-zoom-pro-lomax-110-navy-36158.html", product_id: 5, shop_id: 8, price: "249.9", currency: "EUR", description: "Profitez de votre Roller freeskate ZOOM PRO LOMAX  Navy POWERSLIDE au meilleur prix chez Nomadeshop"},
  {url: "https://itaksport.com/itak-sport/52567-116964-powerslide-zoom-pro-100-inline-skates-senior.html", product_id: 5, shop_id: 18, price: "269.99", currency: "EUR", description: "Powerslide Zoom PRO Lomax  inline skates - Senior"}
])
